### ISSUE TITLE
0.14.12: pytest is failing

### ISSUE THREAD

**Issue by kloczek** [keijack/python-simple-http-server#7]
I'm trying to package your module as an rpm package. So I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes oly locally installed modules
- install .whl file in </install/prefix>
- run pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

Here is pytest output:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-simple-http-server-0.14.12-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-simple-http-server-0.14.12-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/python-simple-http-server-0.14.12
collected 23 items

tests/test_all_ctrls.py .........EEEEEEEEE                                                                                                                           [ 78%]
tests/test_all_ctrls_wsgi.py EEEEE                                                                                                                                   [100%]

================================================================================== ERRORS ==================================================================================
___________________________________________________________ ERROR at setup of CoroutineServerTest.test_coroutine ___________________________________________________________

clz = <class 'tests.test_all_ctrls.CoroutineServerTest'>

    @classmethod
    def setUpClass(clz):
        Thread(target=clz.start_server, daemon=True, name="t").start()
        retry = 0
        while not server.is_ready():
            sleep(1)
            retry = retry + 1
            _logger.info(
                f"server is not ready wait. {retry}/{clz.WAIT_COUNT} ")
            if retry >= clz.WAIT_COUNT:
>               raise Exception("Server start wait timeout.")
E               Exception: Server start wait timeout.

tests/test_all_ctrls.py:51: Exception
-------------------------------------------------------------------------- Captured stdout setup ---------------------------------------------------------------------------
[2022-01-14 16:11:58]-[t]-[http_test:32] INFO: start server in background.
[2022-01-14 16:11:58]-[t]-[simple_http_server.server:101] INFO: Import controllers from module: tests.ctrls.my_controllers
[2022-01-14 16:11:58]-[t]-[simple_http_server.server:101] INFO: Import controllers from module: tests.ctrls.ws_controllers
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:495] INFO: Start server in corouting mode, listen to port: 9090
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:225] DEBUG: [path: /abcde/**] map url regexp ^/abcde/([\w%.\-@!\(\)\[\]\|\$/]+)$ to function: <function fil at 0x7f7ab1f4e430>
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:225] DEBUG: [path: /tuple] map url regexp ^/tuple$ to function: <function filter_tuple at 0x7f7ab1f4e550>
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:225] DEBUG: [path: ] map url regexp ^/abcd to function: <function filter_tuple at 0x7f7ab1f4e550>
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /favicon.ico| with method[] to function <function _favicon at 0x7f7ab158fe50>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /index| with method[] to function <function my_ctrl at 0x7f7ab1f37ca0>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /| with method[] to function <function my_ctrl at 0x7f7ab1f37ca0>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /say_hello| with method[GET] to function <function my_ctrl2 at 0x7f7ab1f37c10>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /say_hello| with method[POST] to function <function my_ctrl2 at 0x7f7ab1f37c10>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /error| with method[] to function <function my_ctrl3 at 0x7f7ab1f37d30>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /中文/coroutine| with method[] to function <function coroutine_ctrl at 0x7f7ab1f37e50>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /exception| with method[] to function <function exception_ctrl at 0x7f7ab1f37ee0>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /upload| with method[POST] to function <function my_upload at 0x7f7ab1f37f70>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /post_txt| with method[GET] to function <function normal_form_post at 0x7f7ab1f4e040>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /post_txt| with method[POST] to function <function normal_form_post at 0x7f7ab1f4e040>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /post_json| with method[POST] to function <function post_json at 0x7f7ab1f4e0d0>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /cookies| with method[] to function <function set_headers at 0x7f7ab1f4e160>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url tuple| with method[] to function <function tuple_results at 0x7f7ab1f4e1f0>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url session| with method[] to function <function test_session at 0x7f7ab1f4e280>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url tuple_cookie| with method[] to function <function tuple_with_cookies at 0x7f7ab1f4e310>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url header_echo| with method[] to function <function header_echo at 0x7f7ab1f4e3a0>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /redirect| with method[] to function <function redirect at 0x7f7ab1f4e4c0>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /params| with method[] to function <function my_ctrl4 at 0x7f7ab1f4e5e0>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /int_status_code| with method[] to function <function return_int at 0x7f7ab1f4e670>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /path_values/{pval}/{path_val}/x| with method[] to function <function my_path_val_ctr at 0x7f7ab1f4e700>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /obj| with method[] to function <function MyController.my_ctrl_mth at 0x7f7ab1f4e9d0>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /obj/hello| with method[GET] to function <function MyController.my_ctrl_mth at 0x7f7ab1f4e9d0>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /obj/hello| with method[POST] to function <function MyController.my_ctrl_mth at 0x7f7ab1f4e9d0>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /obj/hello2| with method[GET] to function <function MyController.my_ctr_mth2 at 0x7f7ab1f4ea60>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /obj/hello2| with method[POST] to function <function MyController.my_ctr_mth2 at 0x7f7ab1f4ea60>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url |^(reg/(.+))$ with method[GET] to function <function MyController.my_reg_ctr at 0x7f7ab1f4eaf0>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url abcde/**| with method[] to function <function wildcard_match at 0x7f7ab1f4e940>.
[2022-01-14 16:11:58]-[t]-[simple_http_server.http_server:119] DEBUG: map url /put/file| with method[PUT] to function <function reader_test at 0x7f7ab1f4eb80>.
[2022-01-14 16:11:59]-[MainThread]-[http_test:48] INFO: server is not ready wait. 1/10
[2022-01-14 16:12:00]-[MainThread]-[http_test:48] INFO: server is not ready wait. 2/10
[2022-01-14 16:12:01]-[MainThread]-[http_test:48] INFO: server is not ready wait. 3/10
[2022-01-14 16:12:02]-[MainThread]-[http_test:48] INFO: server is not ready wait. 4/10
[2022-01-14 16:12:03]-[MainThread]-[http_test:48] INFO: server is not ready wait. 5/10
[2022-01-14 16:12:04]-[MainThread]-[http_test:48] INFO: server is not ready wait. 6/10
[2022-01-14 16:12:05]-[MainThread]-[http_test:48] INFO: server is not ready wait. 7/10
[2022-01-14 16:12:06]-[MainThread]-[http_test:48] INFO: server is not ready wait. 8/10
[2022-01-14 16:12:07]-[MainThread]-[http_test:48] INFO: server is not ready wait. 9/10
[2022-01-14 16:12:08]-[MainThread]-[http_test:48] INFO: server is not ready wait. 10/10
_____________________________________________________________ ERROR at setup of CoroutineServerTest.test_error _____________________________________________________________

clz = <class 'tests.test_all_ctrls.CoroutineServerTest'>

    @classmethod
    def setUpClass(clz):
        Thread(target=clz.start_server, daemon=True, name="t").start()
        retry = 0
        while not server.is_ready():
            sleep(1)
            retry = retry + 1
            _logger.info(
                f"server is not ready wait. {retry}/{clz.WAIT_COUNT} ")
            if retry >= clz.WAIT_COUNT:
>               raise Exception("Server start wait timeout.")
E               Exception: Server start wait timeout.

tests/test_all_ctrls.py:51: Exception
___________________________________________________________ ERROR at setup of CoroutineServerTest.test_exception ___________________________________________________________

clz = <class 'tests.test_all_ctrls.CoroutineServerTest'>

    @classmethod
    def setUpClass(clz):
        Thread(target=clz.start_server, daemon=True, name="t").start()
        retry = 0
        while not server.is_ready():
            sleep(1)
            retry = retry + 1
            _logger.info(
                f"server is not ready wait. {retry}/{clz.WAIT_COUNT} ")
            if retry >= clz.WAIT_COUNT:
>               raise Exception("Server start wait timeout.")
E               Exception: Server start wait timeout.

tests/test_all_ctrls.py:51: Exception
____________________________________________________________ ERROR at setup of CoroutineServerTest.test_filter _____________________________________________________________

clz = <class 'tests.test_all_ctrls.CoroutineServerTest'>

    @classmethod
    def setUpClass(clz):
        Thread(target=clz.start_server, daemon=True, name="t").start()
        retry = 0
        while not server.is_ready():
            sleep(1)
            retry = retry + 1
            _logger.info(
                f"server is not ready wait. {retry}/{clz.WAIT_COUNT} ")
            if retry >= clz.WAIT_COUNT:
>               raise Exception("Server start wait timeout.")
E               Exception: Server start wait timeout.

tests/test_all_ctrls.py:51: Exception
__________________________________________________________ ERROR at setup of CoroutineServerTest.test_header_echo __________________________________________________________

clz = <class 'tests.test_all_ctrls.CoroutineServerTest'>

    @classmethod
    def setUpClass(clz):
        Thread(target=clz.start_server, daemon=True, name="t").start()
        retry = 0
        while not server.is_ready():
            sleep(1)
            retry = retry + 1
            _logger.info(
                f"server is not ready wait. {retry}/{clz.WAIT_COUNT} ")
            if retry >= clz.WAIT_COUNT:
>               raise Exception("Server start wait timeout.")
E               Exception: Server start wait timeout.

tests/test_all_ctrls.py:51: Exception
__________________________________________________________ ERROR at setup of CoroutineServerTest.test_path_value ___________________________________________________________

clz = <class 'tests.test_all_ctrls.CoroutineServerTest'>

    @classmethod
    def setUpClass(clz):
        Thread(target=clz.start_server, daemon=True, name="t").start()
        retry = 0
        while not server.is_ready():
            sleep(1)
            retry = retry + 1
            _logger.info(
                f"server is not ready wait. {retry}/{clz.WAIT_COUNT} ")
            if retry >= clz.WAIT_COUNT:
>               raise Exception("Server start wait timeout.")
E               Exception: Server start wait timeout.

tests/test_all_ctrls.py:51: Exception
___________________________________________________________ ERROR at setup of CoroutineServerTest.test_post_json ___________________________________________________________

clz = <class 'tests.test_all_ctrls.CoroutineServerTest'>

    @classmethod
    def setUpClass(clz):
        Thread(target=clz.start_server, daemon=True, name="t").start()
        retry = 0
        while not server.is_ready():
            sleep(1)
            retry = retry + 1
            _logger.info(
                f"server is not ready wait. {retry}/{clz.WAIT_COUNT} ")
            if retry >= clz.WAIT_COUNT:
>               raise Exception("Server start wait timeout.")
E               Exception: Server start wait timeout.

tests/test_all_ctrls.py:51: Exception
____________________________________________________________ ERROR at setup of CoroutineServerTest.test_static _____________________________________________________________

clz = <class 'tests.test_all_ctrls.CoroutineServerTest'>

    @classmethod
    def setUpClass(clz):
        Thread(target=clz.start_server, daemon=True, name="t").start()
        retry = 0
        while not server.is_ready():
            sleep(1)
            retry = retry + 1
            _logger.info(
                f"server is not ready wait. {retry}/{clz.WAIT_COUNT} ")
            if retry >= clz.WAIT_COUNT:
>               raise Exception("Server start wait timeout.")
E               Exception: Server start wait timeout.

tests/test_all_ctrls.py:51: Exception
______________________________________________________________ ERROR at setup of CoroutineServerTest.test_ws _______________________________________________________________

clz = <class 'tests.test_all_ctrls.CoroutineServerTest'>

    @classmethod
    def setUpClass(clz):
        Thread(target=clz.start_server, daemon=True, name="t").start()
        retry = 0
        while not server.is_ready():
            sleep(1)
            retry = retry + 1
            _logger.info(
                f"server is not ready wait. {retry}/{clz.WAIT_COUNT} ")
            if retry >= clz.WAIT_COUNT:
>               raise Exception("Server start wait timeout.")
E               Exception: Server start wait timeout.

tests/test_all_ctrls.py:51: Exception
_____________________________________________________________ ERROR at setup of WSGIHttpRequestTest.test_error _____________________________________________________________

clz = <class 'tests.test_all_ctrls_wsgi.WSGIHttpRequestTest'>

    @classmethod
    def setUpClass(clz):
        Thread(target=clz.start_server, daemon=False, name="t").start()
        retry = 0
        while not clz.server_ready:
            sleep(1)
            retry = retry + 1
            _logger.info(f"server is not ready wait. {retry}/{clz.WAIT_COUNT} ")
            if retry >= clz.WAIT_COUNT:
>               raise Exception("Server start wait timeout.")
E               Exception: Server start wait timeout.

tests/test_all_ctrls_wsgi.py:55: Exception
-------------------------------------------------------------------------- Captured stdout setup ---------------------------------------------------------------------------
[2022-01-14 16:12:08]-[t]-[http_test:35] INFO: start server in background.
[2022-01-14 16:12:08]-[t]-[simple_http_server.server:101] INFO: Import controllers from module: tests.ctrls.my_controllers
[2022-01-14 16:12:08]-[t]-[simple_http_server.server:101] INFO: Import controllers from module: tests.ctrls.ws_controllers
[2022-01-14 16:12:09]-[MainThread]-[http_test:53] INFO: server is not ready wait. 1/10
[2022-01-14 16:12:10]-[MainThread]-[http_test:53] INFO: server is not ready wait. 2/10
[2022-01-14 16:12:11]-[MainThread]-[http_test:53] INFO: server is not ready wait. 3/10
[2022-01-14 16:12:12]-[MainThread]-[http_test:53] INFO: server is not ready wait. 4/10
[2022-01-14 16:12:13]-[MainThread]-[http_test:53] INFO: server is not ready wait. 5/10
[2022-01-14 16:12:14]-[MainThread]-[http_test:53] INFO: server is not ready wait. 6/10
[2022-01-14 16:12:15]-[MainThread]-[http_test:53] INFO: server is not ready wait. 7/10
[2022-01-14 16:12:16]-[MainThread]-[http_test:53] INFO: server is not ready wait. 8/10
[2022-01-14 16:12:17]-[MainThread]-[http_test:53] INFO: server is not ready wait. 9/10
[2022-01-14 16:12:18]-[MainThread]-[http_test:53] INFO: server is not ready wait. 10/10
___________________________________________________________ ERROR at setup of WSGIHttpRequestTest.test_exception ___________________________________________________________

clz = <class 'tests.test_all_ctrls_wsgi.WSGIHttpRequestTest'>

    @classmethod
    def setUpClass(clz):
        Thread(target=clz.start_server, daemon=False, name="t").start()
        retry = 0
        while not clz.server_ready:
            sleep(1)
            retry = retry + 1
            _logger.info(f"server is not ready wait. {retry}/{clz.WAIT_COUNT} ")
            if retry >= clz.WAIT_COUNT:
>               raise Exception("Server start wait timeout.")
E               Exception: Server start wait timeout.

tests/test_all_ctrls_wsgi.py:55: Exception
__________________________________________________________ ERROR at setup of WSGIHttpRequestTest.test_header_echo __________________________________________________________

clz = <class 'tests.test_all_ctrls_wsgi.WSGIHttpRequestTest'>

    @classmethod
    def setUpClass(clz):
        Thread(target=clz.start_server, daemon=False, name="t").start()
        retry = 0
        while not clz.server_ready:
            sleep(1)
            retry = retry + 1
            _logger.info(f"server is not ready wait. {retry}/{clz.WAIT_COUNT} ")
            if retry >= clz.WAIT_COUNT:
>               raise Exception("Server start wait timeout.")
E               Exception: Server start wait timeout.

tests/test_all_ctrls_wsgi.py:55: Exception
__________________________________________________________ ERROR at setup of WSGIHttpRequestTest.test_path_value ___________________________________________________________

clz = <class 'tests.test_all_ctrls_wsgi.WSGIHttpRequestTest'>

    @classmethod
    def setUpClass(clz):
        Thread(target=clz.start_server, daemon=False, name="t").start()
        retry = 0
        while not clz.server_ready:
            sleep(1)
            retry = retry + 1
            _logger.info(f"server is not ready wait. {retry}/{clz.WAIT_COUNT} ")
            if retry >= clz.WAIT_COUNT:
>               raise Exception("Server start wait timeout.")
E               Exception: Server start wait timeout.

tests/test_all_ctrls_wsgi.py:55: Exception
____________________________________________________________ ERROR at setup of WSGIHttpRequestTest.test_static _____________________________________________________________

clz = <class 'tests.test_all_ctrls_wsgi.WSGIHttpRequestTest'>

    @classmethod
    def setUpClass(clz):
        Thread(target=clz.start_server, daemon=False, name="t").start()
        retry = 0
        while not clz.server_ready:
            sleep(1)
            retry = retry + 1
            _logger.info(f"server is not ready wait. {retry}/{clz.WAIT_COUNT} ")
            if retry >= clz.WAIT_COUNT:
>               raise Exception("Server start wait timeout.")
E               Exception: Server start wait timeout.

tests/test_all_ctrls_wsgi.py:55: Exception
============================================================================= warnings summary =============================================================================
tests/test_all_ctrls.py::CoroutineServerTest::test_coroutine
  /usr/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread t

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/home/tkloczko/rpmbuild/BUILD/python-simple-http-server-0.14.12/tests/test_all_ctrls.py", line 36, in start_server
      server.start(
    File "/home/tkloczko/rpmbuild/BUILD/python-simple-http-server-0.14.12/simple_http_server/server.py", line 153, in start
      _server.start()
    File "/home/tkloczko/rpmbuild/BUILD/python-simple-http-server-0.14.12/simple_http_server/http_server.py", line 515, in start
      self.server.start()
    File "/home/tkloczko/rpmbuild/BUILD/python-simple-http-server-0.14.12/simple_http_server/http_server.py", line 430, in start
      asyncio.run(self.start_server())
    File "/usr/lib64/python3.8/asyncio/runners.py", line 44, in run
      return loop.run_until_complete(main)
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
      return future.result()
    File "/home/tkloczko/rpmbuild/BUILD/python-simple-http-server-0.14.12/simple_http_server/http_server.py", line 418, in start_server
      self.server = await asyncio.start_server(
    File "/usr/lib64/python3.8/asyncio/streams.py", line 94, in start_server
      return await loop.create_server(factory, host, port, **kwds)
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 1463, in create_server
      raise OSError(err.errno, 'error while attempting '
  OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 9090): address already in use

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/test_all_ctrls_wsgi.py::WSGIHttpRequestTest::test_error
  /usr/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread t

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/home/tkloczko/rpmbuild/BUILD/python-simple-http-server-0.14.12/tests/test_all_ctrls_wsgi.py", line 38, in start_server
      wsgi_proxy = server.init_wsgi_proxy(resources={"/public/*": f"{root}/tests/static"})
    File "/home/tkloczko/rpmbuild/BUILD/python-simple-http-server-0.14.12/simple_http_server/server.py", line 278, in init_wsgi_proxy
      proxy.map_filter(ft["url_pattern"], ft["func"])
  TypeError: map_filter() takes 2 positional arguments but 3 were given

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
ERROR tests/test_all_ctrls.py::CoroutineServerTest::test_coroutine - Exception: Server start wait timeout.
ERROR tests/test_all_ctrls.py::CoroutineServerTest::test_error - Exception: Server start wait timeout.
ERROR tests/test_all_ctrls.py::CoroutineServerTest::test_exception - Exception: Server start wait timeout.
ERROR tests/test_all_ctrls.py::CoroutineServerTest::test_filter - Exception: Server start wait timeout.
ERROR tests/test_all_ctrls.py::CoroutineServerTest::test_header_echo - Exception: Server start wait timeout.
ERROR tests/test_all_ctrls.py::CoroutineServerTest::test_path_value - Exception: Server start wait timeout.
ERROR tests/test_all_ctrls.py::CoroutineServerTest::test_post_json - Exception: Server start wait timeout.
ERROR tests/test_all_ctrls.py::CoroutineServerTest::test_static - Exception: Server start wait timeout.
ERROR tests/test_all_ctrls.py::CoroutineServerTest::test_ws - Exception: Server start wait timeout.
ERROR tests/test_all_ctrls_wsgi.py::WSGIHttpRequestTest::test_error - Exception: Server start wait timeout.
ERROR tests/test_all_ctrls_wsgi.py::WSGIHttpRequestTest::test_exception - Exception: Server start wait timeout.
ERROR tests/test_all_ctrls_wsgi.py::WSGIHttpRequestTest::test_header_echo - Exception: Server start wait timeout.
ERROR tests/test_all_ctrls_wsgi.py::WSGIHttpRequestTest::test_path_value - Exception: Server start wait timeout.
ERROR tests/test_all_ctrls_wsgi.py::WSGIHttpRequestTest::test_static - Exception: Server start wait timeout.
================================================================ 9 passed, 2 warnings, 14 errors in 21.51s =================================================================
```

**Comment by keijack** [comment]
Please checkout 0.14.13. It seems in pytest, it will do all the tests and make the tearDownClass after all tests are down, and I use the same server port in all 3 scenarios. I've make the change that 3 ports are used in all the tests which are 9090, 9091 and 9092, please make sure that you have these 3 ports available when running the tests.

**Comment by kloczek** [comment]
Looks like it work now 😄 
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-simple-http-server-0.14.13-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-simple-http-server-0.14.13-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/python-simple-http-server-0.14.13
plugins: hypothesis-6.35.1, forked-1.4.0, cov-3.0.0, xdist-2.5.0, mock-3.6.1, rerunfailures-10.2
collected 23 items

tests/test_all_ctrls.py ..................                                                                                                                           [ 78%]
tests/test_all_ctrls_wsgi.py .....                                                                                                                                   [100%]

============================================================================ 23 passed in 6.74s ============================================================================
```

Thank you and closing.
